/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef SDLAPP_BAKE_CONFIG_H
#define SDLAPP_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#include <ecsx.h>
#include <egspatials.h>
#include <egspatialssystems.h>
#include <egshapes.h>
#include <egbuttons.h>
#include <egwindows.h>
#include <egwindowssdl.h>
#include <egdisplays.h>
#include <egdisplayssdl.h>
#include <eggpus.h>
#include <eggpussdl.h>
#include <egfs.h>
#include <egbase.h>
#include <egmisc.h>
#include <egmath.h>

#endif

