/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef APP1_BAKE_CONFIG_H
#define APP1_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#include <ecsx.h>
#include <egspatials.h>
#include <egspatialssystems.h>
#include <egshapes.h>
#include <egwindows.h>
#include <egwindowssdl.h>
#include <egwindowssdlgl.h>
#include <egcameras.h>
#include <egbuttons.h>
#include <egphysics.h>
#include <egphysicsbox2d.h>
#include <egmath.h>
#include <box2d.h>
#include <egg.h>

#endif

