/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef APP1_BAKE_CONFIG_H
#define APP1_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#include <ecsx.h>
#include <EgSpatials.h>
#include <EgSpatialsSystems.h>
#include <EgShapes.h>
#include <EgWindows.h>
#include <EgWindowsSdl.h>
#include <EgWindowsSdlGl.h>
#include <EgCameras.h>
#include <EgButtons.h>
#include <EgPhysics.h>
#include <egmath.h>
#include <draw.h>

#endif

